import type { GeneratorModel } from '../../data/electricityTypes';
import type { InsuranceType } from '../../data/insuranceTypes';
import type { MarketId } from '../../data/marketRegions';
import type { Worker, Consultant, WorkerJobPosting, WorkerRequest, WorkerRole, ContractType } from '../../data/workerTypes';
import type { OwnedAnimal, AnimalGenes } from '../../engine/animals';
import type { Loan, LoanRecord, SaleRecord, SavingsAccount, TimeDeposit } from '../../engine/banking';
import type { WeatherDay } from '../../engine/climate';
import type { Contract, Buyer, RecurringContract } from '../../engine/contracts';
import type { CoopId, CoopMembership, CoopState } from '../../engine/cooperativeTypes';
import type { CSACommitment, CSASubscriber, CSAWeekLog } from '../../engine/csa';
import type { DynastyState } from '../../engine/dynasty';
import type { Hedgerow, HedgerowType } from '../../engine/hedgerows';
import type { LeaseAgreement, AvailableLease, TenantImprovement } from '../../engine/leases';
import type { ContractorOperation } from '../../engine/machinery';
import type { MarketPrice, NewsEvent } from '../../engine/market';
import type { ActiveShock } from '../../engine/priceEngine';
import type { ProcessingBuilding } from '../../engine/processing';
import type { AESEnrollment, SubsidyPayment } from '../../engine/subsidies';
import type { TimelineState } from '../../engine/timeline';
import type { DrillSpot, Well } from '../../engine/water';
import type { FeedRation } from '../../engine/nutrition';
import type { CompostBatch } from '../../engine/composting';
import type { RestaurantContract, ShowAward, VegBoxSubscriber } from '../../engine/sellingChannels';
import type { MapField } from '../../types/worldMap';
import type { ProcessingBatch, ProcessedItem } from '../../data/processingTypes';
import type { StoredBatch } from '../../engine/storageQuality';
import type { LandParcel } from './land';
import type { AuctionCategory, AuctionListing, AuctionPickup } from './auctions';
import type { ShowEntry, ShowResult } from './animals';
import type { SeedEntry, HybridJob } from './crops';
import type { ElectricityState } from './electricity';
import type { FuturesPosition, InsuranceClaim, InsurancePolicy, MarketOrder, PriceAlert, RivalNewsItem, SeasonGoal } from './economy';
import type {
  DeliveryCargo,
  DeliveryJob,
  HarvestJob,
  MachineRepair,
  OwnedAttachment,
  OwnedMachine,
  OwnedTrailer,
  ReturnOrder,
  TractorJob,
} from './machinery';
import type { HenilBatch, IncubationBatch, ProductionBuildingState } from './processing';
import type { DaySummaryEvent, FairEvent, FieldEvent, GameEvent } from './uiEvents';
import type { FamilyState } from '../../features/family/familyTypes';
import type { FamilyActions } from '../../features/family/familyActions';
import type { ReputationState } from '../../features/reputation/reputationTypes';
import type { NeighborState, NeighborLandOpportunity } from '../../features/neighbors/neighborTypes';
import type { AdvisorStyle, AnnualPlanningState } from './annualPlanning';
import type { ChoiceEventTemplate } from '../../data/choiceEvents';

export interface GameState {
  day: number;
  money: number;
  parcels: LandParcel[];
  animals: OwnedAnimal[];
  animalInventory: Record<string, number>;
  machines: OwnedMachine[];
  prices: MarketPrice[];
  activeShocks: ActiveShock[];
  priceMomentum: Record<string, number>;
  priceHistory15d: Record<string, number[]>;
  npcProductionMultipliers: Record<string, number>;
  npcPriceSignalDays: Record<string, number>;
  fertilizerPrice: number;
  newsEvents: NewsEvent[];
  loans: Loan[];
  savings: SavingsAccount;
  timeDeposits: TimeDeposit[];
  contracts: Contract[];
  buyers: Buyer[];
  recurringContracts: RecurringContract[];
  salesLog: SaleRecord[];
  loanHistory: LoanRecord[];
  forecast: WeatherDay[];
  todayWeather: WeatherDay | null;
  inventory: Record<string, number>;
  inventoryBatches: StoredBatch[];
  hedgerows: Hedgerow[];
  cropsGrownThisYear: string[];
  strawBurnedThisYear: boolean;
  aesEnrollments: AESEnrollment[];
  subsidyLog: SubsidyPayment[];
  activeLeases: LeaseAgreement[];
  availableLeases: AvailableLease[];
  tenantImprovements: TenantImprovement[];
  csaSubscribers: CSASubscriber[];
  csaActive: boolean;
  csaCommitment: CSACommitment;
  csaSeasonStart?: number;
  csaWeeklyLog: CSAWeekLog[];
  priceHistory: Record<string, number[]>;
  productInventory: Record<string, number>;
  buildings: string[];
  declinedTemplates: string[];
  fieldEvents: FieldEvent[];
  listings: AuctionListing[];
  nextAnimalAuctionDay: number;
  pendingPickup: AuctionPickup[];
  daySummary: DaySummaryEvent[] | null;
  prevDayMoney?: number;
  prevDayReputationScore?: number;
  insurances: InsurancePolicy[];
  insuranceClaims: InsuranceClaim[];
  processedInventory: ProcessedItem[];
  activeBatches: ProcessingBatch[];
  harvestedCropIds: string[];
  completedMilestones: string[];
  milestonePopup: { icon: string; title: string; reward: number } | null;
  tutorialSeen: boolean;
  dayOneChecklist: {
    tilled: boolean;
    planted: boolean;
    advanced5: boolean;
    harvested: boolean;
  };
  firstMissionStep: number;
  dismissedHints: string[];
  totalRevenue: number;
  yearEndShown: boolean;
  activeFair: FairEvent | null;
  futures: FuturesPosition[];
  cooperative: { member: boolean; joinDay: number } | null;
  coopMemberships: Partial<Record<CoopId, CoopMembership>>;
  coopStates: Record<CoopId, CoopState>;
  aquiferLevel: number;
  wells: Well[];
  gridWaterActive: boolean;
  gridWaterDailyRate: number;
  legacyReputation: number;
  nearSettlement: boolean;
  soundBarriers: boolean;
  activeSchedule?: {
    harvestWindow: 'twilight' | 'day' | 'night';
    irrigationWindow: 'twilight' | 'day' | 'night';
    machineryWindow: 'twilight' | 'day' | 'night';
  };
  autoSell: Record<string, { enabled: boolean; minPrice: number }>;
  inventoryReserves: Record<string, number>;
  prestige: number;
  workers: Worker[];
  consultant: Consultant | null;
  pendingRequests: WorkerRequest[];
  requestLog: WorkerRequest[];
  jobPostings: WorkerJobPosting[];
  employerReputation: number;
  bankrupt: boolean;
  familyLoanUsedDay: number | null;
  sellPressures: { cropId: string; modifier: number; expiresDay: number }[];
  breedingPairs: Record<string, string>;
  activeEvents: GameEvent[];
  timeline: TimelineState;
  dynasty: DynastyState;
  dynastyAuctionWins: number;
  // Phase 3 — Living History
  family: FamilyState;
  reputation: ReputationState;
  neighbors: NeighborState;
  pendingLandOpportunities: NeighborLandOpportunity[];
  gameSetupComplete: boolean;
  annualPlanning: AnnualPlanningState;
  machineRepairs: MachineRepair[];
  attachments: OwnedAttachment[];
  trailers: OwnedTrailer[];
  tractorJobs: TractorJob[];
  deliveryJobs: DeliveryJob[];
  productionBuildings: ProductionBuildingState[];
  processingBuildings: ProcessingBuilding[];
  animalWelfareScores: Record<string, number>;
  milkGrades: Record<string, 'A' | 'B' | 'C'>;
  lastSyntheticInputDay: number;
  sirePenAnimalIds: string[];
  vetRoomOwned: boolean;
  medicineCabinetOwned: boolean;
  hasCCTV: boolean;
  sickBayCapacity: number;
  slurryLevel: number;
  slurryCapacity: number;
  silageLevel: number;
  silageCapacity: number;
  biogasMode: 'income' | 'fuel';
  incubationQueue: IncubationBatch[];
  hatcheryCapacity: number;
  harvestJobs: HarvestJob[];
  npcFarms: import('../../engine/competitors').NPCFarmRuntime[];
  rivalNews: RivalNewsItem[];
  seasonGoals: SeasonGoal[];
  seasonGoalSeason: string;
  seasonStartMoney: number;
  seasonStartRevenue: number;
  seasonHarvestCount: number;
  seedVault: SeedEntry[];
  hybridJobs: HybridJob[];
  cropQualityMap: Record<string, number>;
  henilQueue: HenilBatch[];
  grainMissedDays: number;
  hayMissedDays: number;
  animalsManuallyFed: boolean;
  savedRations: Record<string, FeedRation>;
  solidManureKg: number;
  cropResidueKg: number;
  compostInventoryKg: number;
  compostBatches: CompostBatch[];
  digestateKg: number;
  soilLabBuilt: boolean;
  pendingAnalyses: Array<{ parcelId: string; arrivesDay: number }>;
  colmenaNegligenceStartDay: Record<string, number>;
  soundEnabled: boolean;
  hapticEnabled: boolean;
  musicEnabled: boolean;
  animalPrices: Record<string, number>;
  personalRecords: {
    peakMoney: number;
    totalHarvests: number;
    bestSeasonRevenue: number;
    longestDay: number;
  };
  seasonalEvent: { type: 'heat_wave' | 'flood' | 'frost'; startDay: number; endsDay: number; severity: number } | null;
  farmName: string;
  farmStyle: 'crop_focus' | 'livestock' | 'market_trader' | 'balanced';
  difficulty: import('../../engine/difficulty').Difficulty;
  fuel: number;
  fuelPrice: number;
  priceAlerts: PriceAlert[];
  showEntries: ShowEntry[];
  showResults: ShowResult[];
  showWindowOpen: boolean;
  marketOrders: MarketOrder[];
  selectedMarket: MarketId;
  electricity: ElectricityState;
  purchaseProductionBuilding: (buildingTypeId: string) => void;
  assignWorkerToBuilding: (buildingId: string, workerId: string) => void;
  unassignWorkerFromBuilding: (buildingId: string, workerId: string) => void;
  installEquipment: (buildingId: string, equipmentItemId: string) => void;
  performDeepClean: (buildingId: string, useContractor: boolean) => void;
  setSoundEnabled: (enabled: boolean) => void;
  setHapticEnabled: (enabled: boolean) => void;
  setMusicEnabled: (enabled: boolean) => void;
  setDifficulty: (d: import('../../engine/difficulty').Difficulty) => void;
  performPrestige: () => void;
  counterOfferContract: (templateId: string, mod: 'price' | 'quantity' | 'deadline') => void;
  upgradeAnimalGene: (animalId: string, gene: keyof AnimalGenes) => void;
  sellSeedBatch: (seedEntryId: string) => void;
  buyMarketSeed: (cropId: string) => void;
  cureDisease: (parcelId: string) => void;
  plantCropBatch: (cropId: string) => void;
  setFarmName: (name: string) => void;
  addPriceAlert: (cropId: string, targetPrice: number, direction: 'above' | 'below') => void;
  removePriceAlert: (alertId: string) => void;
  placeMarketOrder: (cropId: string, quantity: number, targetPrice: number, termDays: number) => void;
  cancelMarketOrder: (orderId: string) => void;
  setSelectedMarket: (marketId: MarketId) => void;
  buyFuel: (litres: number) => void;
  enterAnimalShow: (animalId: string) => void;
  withdrawAnimalShow: (animalId: string) => void;
  advanceDay: () => void;
  advanceDays: (n: number) => void;
  setTimeline: (tl: TimelineState) => void;
  performHandoff: () => void;
  earnKnowledge: (id: string) => void;
  triggerVoluntaryHandoff: () => void;
  assignHydrogeologist: (parcelId: string) => void;
  startDrilling: (wellId: string, spotId: string, targetFlowRate: number) => void;
  installPump: (wellId: string, pumpTier: 1 | 2 | 3) => void;
  connectParcel: (wellId: string, parcelId: string) => void;
  disconnectParcel: (wellId: string, parcelId: string) => void;
  setGridWater: (active: boolean) => void;
  buyParcel: (parcelId: string) => void;
  plantCrop: (parcelId: string, cropId: string, hectares: number) => void;
  harvestCrop: (parcelId: string) => void;
  sellCrop: (cropId: string, units: number, marketId?: MarketId) => void;
  buyAnimal: (typeId: string, sex: 'male' | 'female') => void;
  addToHenil: () => void;
  feedAnimals: () => void;
  saveRation: (animalTypeId: string, ration: FeedRation) => void;
  sellAnimal: (animalId: string) => void;
  collectAnimalProduction: (animalId: string) => void;
  sellAnimalProduct: (productType: string, units: number) => void;
  breedAnimal: (animalId: string) => void;
  cullAnimal: (animalId: string) => void;
  treatAnimal: (animalId: string) => void;
  buyMachine: (typeId: string) => void;
  requestLoan: (principal: number, termDays: number, label: string) => void;
  repayLoan: (loanId: string) => void;
  depositSavings: (amount: number) => void;
  withdrawSavings: (amount: number) => void;
  acceptContract: (templateId: string) => void;
  declineContract: (templateId: string) => void;
  deliverCrop: (contractId: string, amount: number) => void;
  signRecurringContract: (
    buyerId: string,
    cropId: string,
    amountPerDelivery: number,
    frequencyDays: 7 | 14 | 30,
    durationSeasons: number,
  ) => void;
  deliverToRecurringContract: (contractId: string, amountDelivered: number) => void;
  cancelRecurringContract: (contractId: string) => void;
  applySoilAmendment: (parcelId: string, amendment: 'lime' | 'sulfur' | 'subsoiler') => void;
  applySoilNPK: (parcelId: string, productId: string) => void;
  plantCoverCrop: (parcelId: string, coverCropId: string) => void;
  buyProduct: (productId: string) => void;
  buyBuilding: (buildingId: string) => void;
  resolveFieldEvent: (eventId: string, productId: string) => void;
  clearWeeds: (parcelId: string) => void;
  linkParcelToColmena: (parcelId: string, colmenaId: string | null) => void;
  orderSoilAnalysis: (parcelId: string) => void;
  applyPrecisionInputs: (parcelId: string) => void;
  startCompostBatch: (manureKg: number, residueKg: number) => void;
  turnCompostBatch: (batchId: string) => void;
  waterCompostBatch: (batchId: string) => void;
  collectCompostBatch: (batchId: string) => void;
  applyCompost: (parcelId: string, kg: number) => void;
  fertilizeCrop: (parcelId: string, productId: string) => void;
  applyLime: (parcelId: string, type: 'agricultural' | 'dolomitic') => void;
  applyGypsum: (parcelId: string) => void;
  applyLeachingFlush: (parcelId: string) => void;
  applySubsoiling: (parcelId: string) => void;
  listItem: (params: {
    category: AuctionCategory;
    animalId?: string;
    cropId?: string;
    cropQuantity?: number;
    machineId?: string;
    startingBid: number;
    reservePrice: number;
    durationDays: 3 | 7 | 14;
  }) => void;
  withdrawListing: (listingId: string) => void;
  placeBid: (listingId: string, amount: number) => void;
  clearDaySummary: () => void;
  buyInsurance: (type: InsuranceType) => void;
  cancelInsurance: (policyId: string) => void;
  processProduct: (recipeId: string, batches: number) => void;
  sellProcessed: (productId: string, units: number) => void;
  openTimeDeposit: (amount: number, termDays: number, rate: number) => void;
  closeTimeDeposit: (depositId: string) => void;
  clearMilestonePopup: () => void;
  claimSeasonGoalReward: (goalId: string) => void;
  resetGame: () => void;
  markTutorialSeen: () => void;
  markDayOneStep: (step: 'tilled' | 'planted' | 'advanced5' | 'harvested') => void;
  dismissHint: (id: string) => void;
  markYearEndShown: () => void;
  installGreenhouse: (parcelId: string) => void;
  removeGreenhouse: (parcelId: string) => void;
  openFuture: (cropId: string, quantity: number, termDays: number) => void;
  joinCooperative: () => void;
  leaveCooperative: () => void;
  joinCoop: (coopId: CoopId, sharesToBuy: number) => void;
  leaveCoop: (coopId: CoopId) => void;
  deliverToCoop: (coopId: CoopId, itemId: string, volume: number) => void;
  voteAGM: (coopId: CoopId, vote: 'yes' | 'no') => void;
  submitCounterProposal: (coopId: CoopId, changes: Partial<import('../../engine/cooperativeTypes').CoopTerms>) => void;
  bookCoopEquipment: (coopId: CoopId, equipmentId: string, day: number) => void;
  harvestAllReady: () => void;
  collectAllProduction: () => void;
  setAutoSell: (cropId: string, settings: { enabled: boolean; minPrice: number } | null) => void;
  setInventoryReserve: (cropId: string, qty: number) => void;
  startNewSeason: () => void;
  hireWorker: (typeId: WorkerRole) => void;
  fireWorker: (workerId: string) => void;
  postVacancy: (role: WorkerRole, contractType: ContractType, offeredWage: number) => void;
  closePosting: (postingId: string) => void;
  hireApplicant: (postingId: string, applicantId: string) => void;
  approveRequest: (requestId: string) => void;
  denyRequest: (requestId: string) => void;
  chooseBranch: (workerId: string, branchId: string) => void;
  startCertStudy: (workerId: string, certId: string) => void;
  setWorkerNightShift: (workerId: string, enabled: boolean) => void;
  hireConsultant: () => void;
  installIrrigation: (parcelId: string) => void;
  renegotiateLoan: (loanId: string, extraDays: 30 | 60 | 90) => void;
  takeBankruptcyLoan: () => void;
  clearBankruptcy: () => void;
  takeFamilyLoan: () => void;
  setBreedingPair: (femaleId: string, maleId: string) => void;
  clearBreedingPair: (femaleId: string) => void;
  startHybridization: (cropId: string, parentAId: string, parentBId: string) => void;
  selectSeedForParcel: (parcelId: string, seedEntryId: string | null) => void;
  startRepair: (machineId: string) => void;
  buyAttachment: (typeId: string) => void;
  buyTrailer: (typeId: string) => void;
  hitchTrailer: (trailerId: string, truckId: string | null) => void;
  assignJob: (tractorId: string, attachmentId: string, operation: 'till' | 'plant' | 'spray' | 'spread_slurry', parcelIds: string[], cropId?: string) => void;
  assignHarvestJob: (combineId: string, parcelIds: string[]) => void;
  hireContractor: (operation: ContractorOperation, parcelIds: string[], cropId?: string) => void;
  dispatchDelivery: (params: {
    truckId: string;
    trailerId: string;
    driverId: string;
    cargo: DeliveryCargo[];
    marketId: 'local' | 'city' | 'export';
    returnOrders: ReturnOrder[];
  }) => void;
  buyProcessingBuilding: (buildingTypeId: string) => void;
  upgradeProcessingBuilding: (buildingId: string) => void;
  assignWorkerToProcessingBuilding: (buildingId: string, workerId: string) => void;
  unassignWorkerFromProcessingBuilding: (buildingId: string, workerId: string) => void;
  installColdStorage: (buildingId: string) => void;
  mapFields: MapField[];
  mapPanX: number;
  mapPanY: number;
  mapZoom: number;
  selectedMapFieldId: string | null;
  selectMapField: (id: string | null) => void;
  buyMapField: (id: string) => void;
  scoutMapField: (id: string) => void;
  savePanZoom: (x: number, y: number, zoom: number) => void;
  designateAsSire: (animalId: string) => void;
  removeFromSirePen: (animalId: string) => void;
  spreadSlurry: () => void;
  fillSilagePit: (kgGrass: number) => void;
  setBiogasMode: (mode: 'income' | 'fuel') => void;
  queueEggsForIncubation: (typeId: string, quantity: number) => void;
  upgradeGridTier: () => void;
  buySolarPanels: (count: number) => void;
  buyWindTurbines: (count: number) => void;
  buildBiogasPlant: () => void;
  buildBiomassCHP: () => void;
  loadBiomassStraw: () => void;
  buildHeatPipeNetwork: () => void;
  buyBatteryBanks: (count: number) => void;
  buyGenerator: (model: GeneratorModel) => void;
  refuelGenerator: (litres: number) => void;
  toggleGenerator: () => void;
  serviceEquipment: (type: 'solar' | 'wind' | 'battery') => void;
  addSurgeProtector: (buildingId: string) => void;
  beneficialInsectsActive: boolean;
  cropConsultantParcelIds: string[];
  treatPest: (parcelId: string, productId: string) => void;
  buyBeneficialInsects: () => void;
  assignCropConsultant: (parcelIds: string[]) => void;
  setTillageSystem: (parcelId: string, system: 'conventional' | 'reduced' | 'notill') => void;
  installHedgerow: (parcelId: string, edge: 'north' | 'south' | 'east' | 'west', type: HedgerowType) => void;
  enrollAES: (schemeId: string, parcelIds: string[]) => void;
  startOrganicTransition: (parcelId: string) => void;
  fileContaminationAppeal: (parcelId: string) => void;
  signLease: (availableLeaseIndex: number, acceptImprovementClause: boolean) => void;
  cancelLease: (leaseId: string) => void;
  toggleCSA: () => void;
  setCSACommitment: (commitment: CSACommitment) => void;
  setWorkerShiftPreference: (workerId: string, pref: 'twilight' | 'day' | 'night' | 'any') => void;
  reputationHistory: { day: number; delta: number; reason: string }[];
  farmShop: {
    tier: 0 | 1 | 2 | 3;
    openDays: boolean[];
    openHours: number;
    assignedWorkerIds: string[];
  };
  restaurantContracts: RestaurantContract[];
  vegBoxSubscribers: VegBoxSubscriber[];
  onlineShopActive: boolean;
  onlineShopAllocations: Record<string, number>;
  farmCafeOpen: boolean;
  farmCafeWorkerIds: string[];
  awardHistory: ShowAward[];
  productAwardBonuses: Record<string, number>;
  buyFarmShopUpgrade: () => void;
  setShopHours: (openDays: boolean[], openHours: number) => void;
  assignShopWorker: (workerId: string) => void;
  unassignShopWorker: (workerId: string) => void;
  toggleOnlineShop: () => void;
  setOnlineAllocation: (productId: string, units: number) => void;
  toggleFarmCafe: () => void;
  assignCafeWorker: (workerId: string) => void;
  unassignCafeWorker: (workerId: string) => void;
  enterAgriculturalShow: (productId: string, batchId: string) => void;
  // Phase 3 — Family actions (FamilyActions)
  makeLifeEventChoice: FamilyActions['makeLifeEventChoice'];
  setFamilyMemberRole: FamilyActions['setFamilyMemberRole'];
  initiateCoOwnershipAction: FamilyActions['initiateCoOwnershipAction'];
  applyFrictionChoiceAction: FamilyActions['applyFrictionChoiceAction'];
  resolveBuyoutAction: FamilyActions['resolveBuyoutAction'];
  completeGameSetup: FamilyActions['completeGameSetup'];
  generateAnnualPlan: (advisor: AdvisorStyle) => void;
  replaceAnnualPlanGoal: (goalId: string) => void;
  removeAnnualPlanGoal: (goalId: string) => void;
  adjustAnnualPlanGoal: (goalId: string, target: number) => void;
  approveAnnualPlan: () => void;
  dismissAnnualPlanRecommendation: (id: string) => void;
  completeAnnualPlanReview: () => void;
  // Choice events
  pendingChoiceEvent: ChoiceEventTemplate | null;
  firedChoiceEventIds: string[];
  resolveChoiceEvent: (optionIndex: number) => void;
}
